# Generated by Django 4.0.1 on 2023-04-03 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Info', models.CharField(max_length=1250)),
                ('Suggested_Url', models.CharField(max_length=100)),
                ('Picture', models.ImageField(default='media/IMG-20220304-WA0002-1.jpg', upload_to='media/Ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Utensil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Info', models.CharField(max_length=1250)),
                ('Suggested_Url', models.CharField(max_length=100)),
                ('Picture', models.ImageField(default='media/IMG-20220304-WA0002-1.jpg', upload_to='media/Utensils')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.ManyToManyField(to='cooker.Ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=350)),
                ('Chef', models.CharField(max_length=50)),
                ('Tutorial', models.CharField(max_length=1250)),
                ('Tutorial_Link', models.CharField(max_length=100)),
                ('Cooking_Time', models.IntegerField(default=5)),
                ('Rating', models.IntegerField(default=10)),
                ('Image', models.ImageField(default='media/IMG-20220304-WA0002-1.jpg', upload_to='media/')),
                ('ingredients', models.ManyToManyField(to='cooker.Ingredient')),
                ('utensils', models.ManyToManyField(to='cooker.Utensil')),
            ],
        ),
    ]
