# Generated by Django 4.0.1 on 2023-04-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_ings',
            field=models.IntegerField(default=1),
        ),
    ]
