# Generated by Django 4.0.1 on 2023-04-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooker', '0002_profile_no_ings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.CharField(default='chicken', max_length=500),
        ),
    ]
