# Generated by Django 4.0.1 on 2023-04-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooker', '0004_remove_food_ingredients_food_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='available',
            name='food',
            field=models.ManyToManyField(to='cooker.Food'),
        ),
        migrations.AddField(
            model_name='profile',
            name='available',
            field=models.ManyToManyField(to='cooker.available'),
        ),
    ]
