# Generated by Django 4.0.1 on 2023-04-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooker', '0005_remove_available_ingredients_available_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='available',
            field=models.ManyToManyField(to='cooker.Food'),
        ),
        migrations.DeleteModel(
            name='available',
        ),
    ]
